export const ActionTypes = {
    ADD_EDIT_APP_PROPERTY: 'ADD_EDIT_APP_PROPERTY',
    ADD_EDIT_APP_PROP_STORE: 'ADD_EDIT_APP_PROP_STORE',
    REMOVE_APP_PROP_STORE: 'REMOVE_APP_PROP_STORE',
    SUBMIT_SCHEDULE_ROOM: 'SUBMIT_SCHEDULE_ROOM',
    SUBMIT_GET_ROOMS: 'SUBMIT_GET_ROOMS',
    GET_ALL_ROOMS: 'GET_ALL_ROOMS',
    GET_ROOMS_AVAILABILITY: 'GET_ROOMS_AVAILABILITY',
    SHOW_MODAL: 'SHOW_MODAL',
    SHOW_MODAL_STORE: 'SHOW_MODAL_STORE',
    CLOSE_MODAL: 'CLOSE_MODAL',
    CLOSE_MODAL_STORE: 'CLOSE_MODAL_STORE'

}