server:
  port: 8081
spring:
  application:
    name: calendar-service-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bookaroom-fon.eu.auth0.com/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/calendar
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        jdbc.batch_size: 50
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
services:
  notification-services:
    url: 'http://localhost:8083'
    enabled: false
auth0:
  audience: https://bookaroom-fon.eu.auth0.com/api/v2/
