server:
  port: 8081
spring:
  application:
    name: calendar-service-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/calendar
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        jdbc.batch_size: 50
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false

services:
  room-services:
    url: 'http://localhost:8082'
