server:
  port: 8083
spring:
  application:
    name: notification-service-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bookaroom-fon.eu.auth0.com/
features:
  sns:
    accessKey: AKIAVT6RKMRALECJI2PJ
    secretKey: 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
    serviceEndpoint: sns.us-east-1.amazonaws.com
    region: us-east-1
  ses:
    accessKey: AKIAVT6RKMRAGUB7QNEU
    secretKey: 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
    serviceEndpoint: https://email.eu-central-1.amazonaws.com
    region: eu-central-1
auth0:
  audience: https://bookaroom-fon.eu.auth0.com/api/v2/