server:
  port: 8083
spring:
  application:
    name: notification-service-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://bookaroom-fon.eu.auth0.com/
features:
  sns:
    accessKey: AKIAVT6RKMRALJR3GCWV
    secretKey: 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
    serviceEndpoint: sns.us-east-1.amazonaws.com
    region: us-east-1
  ses:
    accessKey: AKIAVT6RKMRAPQDRSIFF
    secretKey: 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
    serviceEndpoint: https://email.eu-central-1.amazonaws.com
    region: eu-central-1
auth0:
  audience: https://bookaroom-fon.eu.auth0.com/api/v2/