openapi: 3.0.0
info:
  title: notification-service
  version: '0.0.1'
  description: notification service
  contact:
    email: julijaciric93@gmail.com
    name: Julija Ciric
servers:
  - url: 'http://localhost:8080'
    description: Local Dev
tags:
  - name: email
    description: email APIs
  - name: sms
    description: sms APIs
paths:
  /emails:
    post:
      summary: Endpoint to send an email
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
        description: Send Email Request
        required: true
      responses:
        '200':
          description: OK
        '204':
          description: NO_CONTENT
      description: Send an emails
      security:
        - bearerAuth: [ ]
      tags:
        - email
  /text-messages:
    post:
      summary: Endpoint to send sms
      operationId: sendSMS
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSMSRequest'
        description: Send Email Request
        required: true
      responses:
        '200':
          description: OK
        '204':
          description: NO_CONTENT
      description: Send sms
      security:
        - bearerAuth: [ ]
      tags:
        - sms
components:
  securitySchemes:
    bearerAuth:
      name: Authorization
      type: apiKey
      in: header
      description: ''
  schemas:
    SendEmailRequest:
      type: object
      title: Send email request
      properties:
        to:
          type: string
        subject:
          type: string
          deprecated: true
        template:
          type: string
        variables:
          type: object
      required:
        - to
        - template
    SendSMSRequest:
      properties: 
        receiver:
          type: string
        message:
          type: string
        senderId:
          type: string