server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/facilities
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1
