server:
  port: 8082
spring:
  application:
    name: room-service-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/facilities
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.batch_size: 50
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/
  instance:
    statusPageUrlPath: ${server.servletPath}/info
    healthCheckUrlPath: ${server.servletPath}/health